version: 0.0
os: linux

files:
  - source: target/webapp-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu
  - source: cloudwatch-config.json
    destination: /home/ubuntu/opt


hooks:
  ApplicationStop:
    - location: ./codedeploy/appstop.sh
      timeout: 180
      runas: ubuntu

  BeforeInstall:
    - location: ./codedeploy/beforeInstall.sh
      timeout: 180
      runas: ubuntu

  AfterInstall:
    - location: ./codedeploy/afterInstall.sh
      timeout: 180
      runas: ubuntu

  ApplicationStart:
    - location: ./codedeploy/appstart.sh
      timeout: 180
      runas: ubuntu



