version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  pr_check:
    steps:
      - run: mvn clean
      - run: mvn install


  build:
    steps:
      - run: mvn clean
      - run: mvn install




workflows:
  version2:

  pr-check:
    jobs:
      - pr_check

  build_deploy:
    jobs:
      - build

