version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  pr-check:
    jobs:
      pr_check:
        - maven/test # checkout, build, test, and upload test results
  build_deploy:
    jobs:
      build:
        - maven/test # checkout, build, test, and upload test results

