version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  pr-check:
    jobs:
      - maven/test # checkout, build, test, and upload test results

  build_deploy:
    jobs:
      build:
        branches:
          only:
            - master
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - checkout
        - run:
            name: build
            command: |
              - maven/test # checkout, build, test, and upload test results




