#version: 2.1
#
#orbs:
#  maven: circleci/maven@0.0.12
#
#workflows:
#  pr-check:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results
#
#  build_deploy:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results
#############################################################################
#      build:
#        branches:
#          only:
#            - master
#      docker:
#        - image: circleci/openjdk:8-jdk
#      steps:
#        - checkout
#        - run:
#            name: build
#            command: |
#              - maven/test # checkout, build, test, and upload test results



###################
#jobs:
#  pr_check:
#    docker:
#      - image: circleci/openjdk:8-jdk
#    steps:
#      - checkout
#      - run: mvn clean install
#  build:
#    docker:
#      - image: circleci/openjdk:8-jdk
#    steps:
#      - checkout
#      - run:
#          command: |
#            mvn clean install
#            mvn test
########################################
jobs:
  pr_check:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          command: |
            mvn clean install
            mvn test
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          command: |
            mvn clean install
            mvn test

workflows:
  version: 2
  pr-check:
    jobs:
      - pr_check
  build_deploy:
    jobs:
      - build



