#version: 2.1
#
#orbs:
#  maven: circleci/maven@0.0.12
#
#workflows:
#  pr-check:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results
#
#  build_deploy:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results
#############################################################################
#      build:
#        branches:
#          only:
#            - master
#      docker:
#        - image: circleci/openjdk:8-jdk
#      steps:
#        - checkout
#        - run:
#            name: build
#            command: |
#              - maven/test # checkout, build, test, and upload test results



###################
#jobs:
#  pr_check:
#    docker:
#      - image: circleci/openjdk:8-jdk
#    steps:
#      - checkout
#      - run: mvn clean install
#  build:
#    docker:
#      - image: circleci/openjdk:8-jdk
#    steps:
#      - checkout
#      - run:
#          command: |
#            mvn clean install
#            mvn test
########################################
version: 2.1
jobs:
  pr_check:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          command: |
            mvn clean install
            mvn test
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install ZIP, AWS CLI and build JAR
          command: |
            sudo apt-get update && sudo apt-get install wget zip unzip -y
            sudo apt-get install -y python3-pip
            sudo pip3 install awscli
            echo "AWS VERSION"
            aws --version
            mvn clean install
      - run:
          name: Create ZIP file
          command: |
            echo "Current build number - ${CIRCLE_BUILD_NUM}"
            pwd
            ls -al
            echo "Create artifacts directory"
            mkdir artifacts
            cd artifacts/
            echo "Contents inside artifacts directory"
            ls -al
            cd ..
            chmod 755 artifacts
            zip -r csye6225-webapp-${CIRCLE_BUILD_NUM}.zip target/webapp-0.0.1-SNAPSHOT.jar codedeploy/*.sh appspec.yml cloudwatch-config.json webapp.sh
            pwd
            ls -al
            chmod 755 csye6225-webapp-${CIRCLE_BUILD_NUM}.zip
            sudo mv csye6225-webapp-${CIRCLE_BUILD_NUM}.zip artifacts
            echo "Go Inside artifacts directory"
            cd artifacts/
            echo "Contents inside artifacts directory"
            ls -al
            pwd
            cd ..
            ls -al

      - run:
          name: Upload ZIP to S3
          command: |
            pwd
            cd artifacts/
            chmod 755 csye6225-webapp-${CIRCLE_BUILD_NUM}.zip
            ls -al
            aws s3 cp csye6225-webapp-${CIRCLE_BUILD_NUM}.zip s3://codedeploy.ankitpatro.me

      - run:
          name: Create Deployment
          command: aws deploy create-deployment --application-name csye6225-webapp --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name csye6225-webapp-deployment --description "CSYE6225 - Codedeploy" --region=${AWS_REGION} --s3-location bucket=codedeploy.ankitpatro.me,bundleType=zip,key=csye6225-webapp-${CIRCLE_BUILD_NUM}.zip



  install_aws_cli:
    docker:
      - image: circleci/python:3.6.8-jessie
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get update && sudo apt-get install wget zip unzip -y
      - run:
          command: |
            sudo pip3 install awscli


workflows:
  version: 2
  pr-check:
    jobs:
      - pr_check
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master





