-- CREATE TABLE user_data (
--     email VARCHAR(100) NOT NULL PRIMARY KEY ,
--     password VARCHAR(100) NOT NULL,
--     first_name VARCHAR(100) NOT NULL,
--     last_name VARCHAR(100) NOT NULL
-- );
--
-- CREATE TABLE sruti(
-- name VARCHAR (100) PRIMARY KEY
-- );